### ISSUE TITLE
Question or issue about groups

### ISSUE THREAD

**Issue by martinisraelsen** [jcgueriaud1/sortable-layout#14]
Hi Jean-Christophe,

I'm trying out the sortable drag-drop component and it seems very good. I did a mock up of a simple list editor where a user can add one or more rows and for each row add one or more fields. In the mock up, you can drag the fields between the rows and also re-order the rows. So far so good.

One issue I noticed, is that when you drag a field from one row to another, the drag-drop mechanism allows you to drop the field between the rows. Is this behaviors as designed? It was my impression that you should not be able to drop the field between the rows as they are not in the same group.

Also if a field is dropped between the rows, it becomes unmoveable and you can't move it back to a row (probably because it's not in the same group).

I have attached a simple program you can run with mvn jetty:run as well as a screen shot with a field between the rows.

Any suggestion is appreciated.

<img width="552" alt="layout-editor-drag-drop" src="https://user-images.githubusercontent.com/6271003/130870205-c77eddcc-1665-4d28-8097-c00732ec0104.png">
[layout-editor.zip](https://github.com/jcgueriaud1/sortable-layout/files/7050277/layout-editor.zip)

**Comment by jcgueriaud1** [comment]
Version 1.1.4 has been released with a brand new demo. Thanks a lot :)

https://jeanchristophe.app.fi/sortable-layout-demo/layout-editor
