### ISSUE TITLE
Temporarily disable sorting of specific elements in SortableLayout based on display size dynamically?

### ISSUE THREAD

**Issue by MarekChr** [jcgueriaud1/sortable-layout#24]
Is there a way to temporarily disable sorting of specific element in SortableLayout with some class name or property? I am using SortableLayout, however in mobile view I can not scroll because elements are actually being selected and dragged.

**Comment by jcgueriaud1** [comment]
You can disable the sorting based on a classname. You have an example here:

```
UnorderedList list = new UnorderedList();
list.add(new ListItem("item 1"));
ListItem listItemFilterable = new ListItem("item 2 - is not draggable");
listItemFilterable.addClassName("ignore-elements");
list.add(listItemFilterable);
list.add(new ListItem("item 3"));
SortableConfig sortableConfig = new SortableConfig();
sortableConfig.addFilter("ignore-elements");
SortableLayout sortableLayout = new SortableLayout(list, sortableConfig);
```

And the demo here: https://jeanchristophe.app.fi/sortable-layout-demo/ (Filter example)

I'm not sure if it will help you for your usecase.

I would probably use an icon to sort only when you are holding the icon like the card example (on the right side): https://jeanchristophe.app.fi/sortable-layout-demo/card

**Comment by MarekChr** [comment]
@jcgueriaud1 This is really nice, however, I need it for mobile view and class names are present for components throughout all display sizes, which leads me to change issue title to more specific one.

As an example:
```
@media screen and (max-width: 550px) {
    .card-full-width-mobile {
        width: 100%;
    }
}

@media screen and (min-width: 551px) {
    .card-max-width-300-non-mobile {
        max-width: 300px;
        width: auto;
    }
    .card-max-width-400-non-mobile {
        max-width: 400px;
        width: auto;
    }
}
```
I tried to add filter class name ```card-full-width-mobile```, which disables sorting in all display sizes, because class is present both in mobile and non-mobile sizes. I need to disable sorting in mobile size only. Can you help with that?

**Comment by jcgueriaud1** [comment]
You can use `addBrowserWindowResizeListener` to add or remove the classname based on the browser size. There is an example here: https://cookbook.vaadin.com/responsive-grid

You can also retrieverthe client details and disable it if it's a touch device:
```
UI.getCurrent().getPage().retrieveExtendedClientDetails(details -> {
			details.isTouchDevice()
		});
```

**Comment by MarekChr** [comment]
@jcgueriaud1 Thanks, this was really helpful.
